name: build

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**/*.md"
      - "REUSE.toml"
      - "**/*.gitignore"
      - "LICENSES/*"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**/*.md"
      - "REUSE.toml"
      - "**/*.gitignore"
      - "LICENSES/*"
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build (${{matrix.os}})
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, windows]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
